### ISSUE TITLE
[Docs?]: misc ui feedback

### ISSUE THREAD

**Issue by kathydlavoie-ps** [pluralsight/pando#2229]
### Latest version

- [X] I have checked the latest version

### Summary 💡

@bradryanbice and I did a review of the docs site alongside feedback from the survey we recently sent out and came up with a list of mods:

- [x] links have underline
- [x] secondary nav is full width
- [x] usage: examples of how to use them, practical implementation
- [x] guidelines: best practices
- [x] implementation -> code
- [x] disabled buttons in multiple sections -> pulled into #2251 
- [x] right side nav is obvious which section is active -> pulled into #2250
- [x] do & don't sections closer to figma ui -> pulled into #2249 

### Motivation 🔦

UI improvement
